name: dependency-graph
run-name: Generate the complete dependency graph

# Dependency graph currently does not automatically detect transitive dependencies for Maven
# https://github.com/github/roadmap/issues/796

on:
  # remove before merge
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  submit-dep-graph:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Submit Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@v3
